#!/usr/bin/env bash
# gen_status_repo.sh — generate a reproducible ~37,500-file git repo for the benchmark.
#
# Layout: 150 directories x ~250 files each = ~37,500 tracked files
# Content: deterministic mix of .c / .js / .json / .md (no timestamps in content)
# Result:  a clean git repo at <DEST> (all files tracked, working tree clean)
#
# Usage:  bench/gen_status_repo.sh [DEST]
#   DEST defaults to /tmp/bench-repo-37k
#   Prints the final file count on success.

set -euo pipefail

DEST="${1:-/tmp/bench-repo-37k}"
N_DIRS=150
FILES_PER_DIR=250

# Remove any prior run
if [ -d "$DEST" ]; then
    rm -rf "$DEST"
fi
mkdir -p "$DEST"

# Initialise git repo (no network, no gpg, reproducible config)
git -C "$DEST" init -q
git -C "$DEST" config user.email "bench@example.com"
git -C "$DEST" config user.name  "Bench Bot"
git -C "$DEST" config core.autocrlf false
git -C "$DEST" config core.symlinks false

# Content templates — no date/time so the commit is fully deterministic
C_TEMPLATE='// module %s file %d
#include <stdio.h>
int func_%s_%d(int x) { return x * %d; }
'
JS_TEMPLATE='// module %s file %d
function handler%d(req) {
  return { status: 200, body: "module-%s" };
}
module.exports = { handler%d };
'
JSON_TEMPLATE='{ "module": "%s", "index": %d, "version": "1.0.%d", "enabled": true }
'
MD_TEMPLATE='# Module %s

File %d of the benchmark suite.

## Overview

This is a placeholder file with index %d.
'

echo "Generating $N_DIRS dirs x $FILES_PER_DIR files in $DEST..."

for dir_i in $(seq 1 $N_DIRS); do
    dir_name=$(printf "module_%04d" "$dir_i")
    dir_path="$DEST/$dir_name"
    mkdir -p "$dir_path"

    for file_i in $(seq 1 $FILES_PER_DIR); do
        # Rotate through 4 file types deterministically
        ext_mod=$(( (file_i - 1) % 4 ))
        base=$(printf "file_%04d" "$file_i")

        case $ext_mod in
        0)
            fname="$base.c"
            printf "$C_TEMPLATE" "$dir_name" "$file_i" "$dir_name" "$file_i" "$file_i" \
                > "$dir_path/$fname"
            ;;
        1)
            fname="$base.js"
            printf "$JS_TEMPLATE" "$dir_name" "$file_i" "$file_i" "$dir_name" "$file_i" \
                > "$dir_path/$fname"
            ;;
        2)
            fname="$base.json"
            printf "$JSON_TEMPLATE" "$dir_name" "$file_i" "$file_i" \
                > "$dir_path/$fname"
            ;;
        3)
            fname="$base.md"
            printf "$MD_TEMPLATE" "$dir_name" "$file_i" "$file_i" \
                > "$dir_path/$fname"
            ;;
        esac
    done
done

# Add a root-level README so the root dir also has files
printf "# Benchmark repo\nGenerated by gen_status_repo.sh\n" > "$DEST/README.md"

# Stage and commit everything
git -C "$DEST" add -A
git -C "$DEST" commit -q -m "bench: generated repo for status-perf spike"

# Verify clean tree
if ! git -C "$DEST" diff --quiet HEAD; then
    echo "ERROR: working tree not clean after commit" >&2
    exit 1
fi

FILE_COUNT=$(git -C "$DEST" ls-files | wc -l | tr -d ' ')
echo "Done. Tracked files: $FILE_COUNT  Path: $DEST"
